### Set Up
we'll import Pytorch & set the seeds for reproducibility

In [1]:
import numpy as np
import torch

In [2]:
SEED = 1234

In [3]:
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

## Basics
we'll start with some basics

In [4]:
# creating tensors
t1 = torch.tensor([1,2,3])
t2 = torch.tensor(data=[[1,2,3],
                  [4,5,6]])

# printing the tensor
print('tensor: ', t1)
# printing the ranks
print('range: ', len(t1.shape))
# printing the shape of tensors
print('shape: ', t1.shape)

# the tensor t2
print('tensor t2: ', t2)
print('range(t2): ', len(t2.shape))
print('shape(t2): ', t2.shape)

tensor:  tensor([1, 2, 3])
range:  1
shape:  torch.Size([3])
tensor t2:  tensor([[1, 2, 3],
        [4, 5, 6]])
range(t2):  2
shape(t2):  torch.Size([2, 3])


In [5]:
data1 = [1,2,3,4,5,6]
data2 = np.array([1.5,2.6,3.1])
t1 = torch.tensor(data1)
t2 = torch.Tensor(data1)

tt1 = torch.as_tensor(data2)
tt2 = torch.from_numpy(data2)

print('type: ', t1.dtype, t2.dtype)
print('type: ', tt1.dtype, tt2.dtype)

type:  torch.int64 torch.float32
type:  torch.float64 torch.float64


In [6]:
t2 = torch.Tensor(data2)
t2.dtype

torch.float32

## Restructing
we'll start with some shape modifications:
- `.transpose(a,b)`
- `.reshape(a,b)`
- `.resize(a,b)`

![image](https://media.geeksforgeeks.org/wp-content/uploads/20210223235051/Screenshot20210223234901-296x300.png)

In [7]:
# defining tensor
t = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [8]:
print("Reshaping")
print(t.reshape(6,2))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [9]:
print("Resizing")
print(t.resize(2,6))

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


/opt/conda/lib/python3.7/site-packages/torch/_tensor.py:549: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [10]:
print("Transpose")
print(t.transpose(1,0))

Transpose
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


## Mathematical Operations on Tensors in PyTorch
We can perform various mathematical operations on tensors using Pytorch. The code for performing Mathematical operations is the same as in the case with NumPy arrays.

In [11]:
x1 = [i*3 for i in range(1000)]
y1 = [i*5 for i in range(1000, 2000)]
# print(len(x), len(y))
x = torch.tensor(x1)
y = torch.tensor(y1)

In [12]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4, 5, 6])

# addition of two tensors
print("tensor 2 + tensor 1: ", t2 + t1) # apparently it's better than torch.add(x,y)
# substraction of two tensors
print("tensor2 - tensor1: ",torch.sub(t2,t1))
# multiplication of two tensors
print("\ntensor2 * tensor1")
print(torch.mul(t2, t1))

# dividing two tensors
print("\ntensor2 / tensor1")
print(torch.div(t2, t1))


tensor 2 + tensor 1:  tensor([5, 7, 9])
tensor2 - tensor1:  tensor([3, 3, 3])

tensor2 * tensor1
tensor([ 4, 10, 18])

tensor2 / tensor1
tensor([4.0000, 2.5000, 2.0000])


## Pytorch Modules
The PyTorch library modules are essential to create and train neural networks. The three main library modules are **Autograd**, **Optim**, and **nn**.

### 1. nn Module

In [13]:
from torch import nn
model = nn.Sequential(nn.Linear(1,1), nn.Sigmoid())
model

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=True)
  (1): Sigmoid()
)

---


### 2. Autograd Module

In [14]:
t1 = torch.tensor(1.0, requires_grad=True)
t2 = torch.tensor(2.0, requires_grad=True)

# cread variable & gradient
z = 100*t1*t2
z.backward()

# printing gradient
print("dz/t1 : ", t1.grad.data) # derivative of z related to t1 (t2 is considered as const)
print("dz/t2 : ", t2.grad.data)

dz/t1 :  tensor(200.)
dz/t2 :  tensor(100.)


In [15]:
x = torch.rand(3,4, requires_grad=True)
x

tensor([[0.2598, 0.3666, 0.0583, 0.7006],
        [0.0518, 0.4681, 0.6738, 0.3315],
        [0.7837, 0.5631, 0.7749, 0.8208]], requires_grad=True)

### 3. Optim Module

In [16]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01) # defining optimizer
optimizer.zero_grad() #setting gradients to zero
optimizer.step() #parameter updation 
print(optimizer.param_groups)
# optimizer.

[{'params': [Parameter containing:
tensor([[-0.9420]], requires_grad=True), Parameter containing:
tensor([-0.1962], requires_grad=True)], 'lr': 0.01, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'maximize': False}]


## Pytorch Dataset & DataLoader
`torch.utils.data.Dataset`: class contains all the custom Datasets.

we need to implement:
* `__len__()` function: returns the size of the dataset.
* `__getitem__()` function: returns a sample (batch) of the given index from the dataset.

In [17]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [18]:
class data_set(Dataset):
    def __init__(self) -> None:
        numbers = list(range(0,100,1))
        self.data = numbers
    def __len__(self):
        return len(self.data)
        
    def __getitem__(self, index):
        return self.data[index]

dataset = data_set()
print('dataset size: ', dataset.__len__())
print('item at index 10: ', dataset.__getitem__(10))

dataset size:  100
item at index 10:  10


In [19]:
dataloader = DataLoader(dataset, batch_size=10)

In [20]:
for i in dataloader:
    print(i)
# for i, batch in enumerate(dataloader):
#     print(i, batch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])
tensor([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
tensor([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])
tensor([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])
tensor([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])
tensor([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])
tensor([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])


In [21]:
# !pip install --upgrade pip
# !python -m pip install seaborn
# !python3 -m pip install -U seaborn
import seaborn as sns

In [22]:
iris = sns.load_dataset('iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

**N.B:** we can pass `pandas series` to tensors.

In [23]:
# this is just for testing above N.B
# iris[['petal_length', 'petal_width']].values
# x = torch.tensor(iris[['petal_length', 'petal_width']].values)
# x

In [24]:
petal_length = torch.tensor(iris['petal_length'])
petal_width = torch.tensor(iris['petal_width'])

In [25]:
from torch.utils.data.dataset import TensorDataset
dataset  = TensorDataset(petal_length, petal_width)
dataset

In [26]:
dataloader = DataLoader(dataset,batch_size=10, shuffle=True)
for i, batch in enumerate(dataloader):
    print(i, batch)

0 [tensor([1.6000, 1.5000, 5.6000, 4.7000, 5.7000, 4.7000, 1.4000, 4.7000, 6.9000,
        1.5000], dtype=torch.float64), tensor([0.2000, 0.2000, 1.8000, 1.2000, 2.3000, 1.6000, 0.2000, 1.4000, 2.3000,
        0.2000], dtype=torch.float64)]
1 [tensor([3.9000, 4.5000, 4.4000, 4.0000, 1.3000, 5.4000, 5.1000, 6.1000, 5.0000,
        4.2000], dtype=torch.float64), tensor([1.4000, 1.6000, 1.2000, 1.3000, 0.3000, 2.3000, 2.0000, 1.9000, 2.0000,
        1.3000], dtype=torch.float64)]
2 [tensor([4.6000, 4.5000, 4.5000, 6.0000, 5.1000, 4.6000, 3.6000, 4.0000, 4.6000,
        4.4000], dtype=torch.float64), tensor([1.3000, 1.5000, 1.5000, 2.5000, 1.6000, 1.5000, 1.3000, 1.2000, 1.4000,
        1.3000], dtype=torch.float64)]
3 [tensor([4.9000, 3.3000, 1.5000, 1.6000, 4.4000, 4.3000, 6.1000, 4.8000, 5.6000,
        3.5000], dtype=torch.float64), tensor([2.0000, 1.0000, 0.2000, 0.2000, 1.4000, 1.3000, 2.5000, 1.8000, 2.1000,
        1.0000], dtype=torch.float64)]
4 [tensor([1.4000, 1.4000, 4.9000, 5

it looks like this:


![](https://media.geeksforgeeks.org/wp-content/uploads/20210204235848/Screenshot20210204235815.png)

---
## Building Neural Network with PyTorch
1. Dataset Preparation: prepare tensors for Pytorch.
2. Building model: (define input/hidden/output layers & init. weights using `torch.randn()`

3. Forward propagation: feed data to NN, matrix multiplication will be performed.
4. Calculate loss: `Pytorch.nn` contains multiple functions to calculate loss & measure error.
5. Back propagation (`pytorch.optim`): used to optimize weights & update weights to minimize the loss error.

In [27]:
import torch
# training input(x) & output(y)


X = torch.Tensor([[1], [2], [3],
                [4], [5], [6]])
y = torch.Tensor([[5], [10], [15],
                  [20], [25], [30]])

class Model(torch.nn.Module):
    #define layer
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1, 1) # input, output features = (1,1)
    
    # implement forward pass
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred
    
model = torch.nn.Linear(1,1)
# defining the loss func & optimizers

loss_fn = torch.nn.L1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1000):
    # predicting using init weights
    y_pred = model(X.requires_grad_())
    
    # loss calc
    loss = loss_fn(y_pred, y)
    
    # calc gradients
    loss.backward()

    # updating weights
    optimizer.step()
    optimizer.zero_grad() # set grads to zero

#testing on new data
X = torch.Tensor([[10], [40]])  # expected 50, 200
predicted = model(X)
print(predicted)

tensor([[ 49.4636],
        [196.7592]], grad_fn=<AddmmBackward0>)
